# From https://github.com/tidyverse/dplyr/blob/master/.travis.yml

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file
# DO NOT CHANGE THE CODE BELOW
#before_install: R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
before_install: R -q -e 'install.packages(c("remotes", "curl", "testthat", "knitr", "dplyr", "tidygraph", "ggraph", "RcppProgress", "RcppArmadillo", "igraph", "tibble")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: true
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      r_check_args: --as-cran --no-build-vignettes --no-vignettes
      env: 
        - BUILD_PKGDOWN: true
    - os: linux
      dist: trusty
      r: devel
      r_check_args: --as-cran --no-build-vignettes --no-vignettes
#    - os: osx
#      osx_image: xcode9.4
#      r: release
#      r_check_args: --as-cran --no-build-vignettes --no-vignettes

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"

#services
#services:
